export const mockDataForSuggestions = {
	Result: {
		Error: "False",
		Total: 142,
		Query: {
			ApiVersion: "3",
			ApiType: "itemlist",
			TopicId: null,
			ToolId: null,
			CategoryId: null,
			PopulationId: null,
			Keyword: null,
			Who: null,
			Age: null,
			Sex: null,
			Pregnant: null,
			TobaccoUse: null,
			SexuallyActive: null,
			Category: null,
			Lang: "en",
			Type: null,
			ReturnType: "json",
			Callback: null,
			HealthfinderPage: null,
			APiType: "itemlist",
		},
		Language: "English",
		Items: {
			Item: [
				{
					Type: "Topic",
					Id: "25",
					Title: "Keep Your Heart Healthy",
					ParentId: -1,
					TranslationId: "25",
				},
				{
					Type: "Topic",
					Id: "327",
					Title: "Get Enough Folic Acid",
					ParentId: -1,
					TranslationId: "327",
				},
				{
					Type: "Category",
					Id: "112",
					Title: "Questions for the Doctor",
					ParentId: "28",
					TranslationId: "112",
				},
				{
					Type: "Category",
					Id: "124",
					Title: "Health Conditions",
					ParentId: -1,
					TranslationId: "124",
				},
				{
					Type: "Category",
					Id: "125",
					Title: "Doctor Visits",
					ParentId: -1,
					TranslationId: "125",
				},
			],
		},
	},
};
